baseURL = "https://example.com/"
locale = "es"
theme = "hugo-theme-terminal"

pagination.pagerSize = 5

[markup.goldmark.renderer]
  unsafe = true

[params]
  contentTypeName = "posts"
  showMenuItems = 2
  fullWidthTheme = false
  centerTheme = false

[languages]

  [languages.es]
    title = "NELISA"
    copyright = ""

    [languages.es.params]
      subtitle = "tema tipo terminal"
      keywords = ""
      menuMore = "mostrar mas"
      readMore = "leer mas"
      readOtherPosts = "leer otros"

    [languages.es.params.logo]
      logoText = "LINUX COMAND"
      logoHomeLink = "/"

    [languages.es.menu]

      [[languages.es.menu.main]]
        identifier = "about"
        name = "Mas sobre mi"
        url = "/about"

      [[languages.es.menu.main]]
        identifier = "showcase"
        name = "Datos De Linux"
        url = "/showcase"